import type { Sample } from "./types";

function randomWaveform(length = 60): number[] {
  return Array.from({ length }, () => 0.2 + Math.random() * 0.8);
}

export const SAMPLES: Sample[] = [
  {
    id: "1",
    title: "Midnight Groove Loop",
    author: "beatsbyjay",
    authorAvatar: "BJ",
    bpm: 90,
    key: "Am",
    genre: "Lo-Fi",
    duration: 8,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["chill", "guitar", "vinyl"],
    downloads: 3420,
    plays: 18200,
    createdAt: "2024-11-15",
  },
  {
    id: "2",
    title: "808 Trap Banger",
    author: "prodbyDrake",
    authorAvatar: "PD",
    bpm: 140,
    key: "F#m",
    genre: "Trap",
    duration: 4,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["808", "bass", "hard"],
    downloads: 8900,
    plays: 45000,
    createdAt: "2024-12-01",
  },
  {
    id: "3",
    title: "Soulful Keys",
    author: "soulstudio",
    authorAvatar: "SS",
    bpm: 75,
    key: "Dm",
    genre: "R&B",
    duration: 16,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["piano", "soul", "emotional"],
    downloads: 2100,
    plays: 11500,
    createdAt: "2024-10-20",
  },
  {
    id: "4",
    title: "Deep House Chord",
    author: "housevibes",
    authorAvatar: "HV",
    bpm: 124,
    key: "G",
    genre: "House",
    duration: 8,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["chords", "house", "4x4"],
    downloads: 5600,
    plays: 29300,
    createdAt: "2024-12-10",
  },
  {
    id: "5",
    title: "Boom Bap Kit Vol.3",
    author: "vinyldigger",
    authorAvatar: "VD",
    bpm: 95,
    key: "C",
    genre: "Hip-Hop",
    duration: 2,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["drums", "boom bap", "vintage"],
    downloads: 12000,
    plays: 67000,
    createdAt: "2024-09-05",
  },
  {
    id: "6",
    title: "Liquid DnB Arp",
    author: "basslineKing",
    authorAvatar: "BK",
    bpm: 174,
    key: "A#m",
    genre: "Drum & Bass",
    duration: 4,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["arp", "liquid", "synth"],
    downloads: 4300,
    plays: 23100,
    createdAt: "2025-01-08",
  },
  {
    id: "7",
    title: "Ambient Texture Pad",
    author: "cosmicwaves",
    authorAvatar: "CW",
    bpm: 60,
    key: "E",
    genre: "Ambient",
    duration: 32,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["pad", "atmospheric", "texture"],
    downloads: 1900,
    plays: 9800,
    createdAt: "2025-01-20",
  },
  {
    id: "8",
    title: "Pop Vocal Chop",
    author: "chopmaster",
    authorAvatar: "CM",
    bpm: 128,
    key: "C#",
    genre: "Pop",
    duration: 4,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["vocal", "chop", "catchy"],
    downloads: 7200,
    plays: 38500,
    createdAt: "2025-02-03",
  },
  {
    id: "9",
    title: "Techno Kick Loop",
    author: "berlinStudio",
    authorAvatar: "BS",
    bpm: 135,
    key: "D",
    genre: "Techno",
    duration: 4,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["kick", "dark", "industrial"],
    downloads: 6800,
    plays: 32000,
    createdAt: "2025-01-30",
  },
  {
    id: "10",
    title: "Jazz Chord Stab",
    author: "jazzcat99",
    authorAvatar: "JC",
    bpm: 105,
    key: "Bm",
    genre: "Soul",
    duration: 2,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["jazz", "stab", "chords"],
    downloads: 3100,
    plays: 15400,
    createdAt: "2024-11-28",
  },
  {
    id: "11",
    title: "Dusty Vinyl Break",
    author: "crate_digger",
    authorAvatar: "CD",
    bpm: 88,
    key: "Fm",
    genre: "Hip-Hop",
    duration: 8,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["break", "dusty", "loop"],
    downloads: 9400,
    plays: 51000,
    createdAt: "2024-12-22",
  },
  {
    id: "12",
    title: "Future Bass Lead",
    author: "synthwave_pro",
    authorAvatar: "SP",
    bpm: 150,
    key: "G#",
    genre: "Pop",
    duration: 4,
    waveform: randomWaveform(),
    audioUrl: "/audio/mock.mp3",
    tags: ["lead", "future bass", "bright"],
    downloads: 5100,
    plays: 26700,
    createdAt: "2025-02-14",
  },
];

export const GENRES = [
  "Hip-Hop",
  "Trap",
  "Lo-Fi",
  "House",
  "Drum & Bass",
  "Ambient",
  "Pop",
  "R&B",
  "Techno",
  "Soul",
] as const;

export const BPM_RANGES = [
  { label: "Slow (< 80)", min: 0, max: 79 },
  { label: "Mid (80–120)", min: 80, max: 120 },
  { label: "Upbeat (121–140)", min: 121, max: 140 },
  { label: "Fast (141+)", min: 141, max: 999 },
] as const;

export const KEYS = [
  "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B",
  "Cm", "C#m", "Dm", "D#m", "Em", "Fm", "F#m", "Gm", "G#m", "Am", "A#m", "Bm",
] as const;
